version: '2.3'

services:
    openpose_gpu_server:
        container_name: openpose_ubuntu_gpu_container
        image: openpose_ubuntu_gpu_image
        runtime: nvidia
        volumes:
            - ${PWD}/api_server/openpose_wrapper:/home/ubuntu/share/openpose_wrapper
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        build:
            context: api_server/openpose_wrapper
            dockerfile: Dockerfile_gpu
        ports:
            - "5010:5010"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "sudo cp -r /openpose_gpu . && cd openpose_server && python3 app.py --host 0.0.0.0 --port 5010 --debug"
