version: '2.3'

services:
    app:
        container_name: openpose_ubuntu_cpu_container
        image: openpose_ubuntu_cpu_image
        volumes:
            - ${PWD}:/home/ubuntu/share/openpose_wrapper
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        build:
            context: .
            dockerfile: Dockerfile_cpu
        ports:
            - "5011:5011"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "cp -r /openpose_cpu . && /bin/bash"
